services:
  db:
    container_name: database
    image: mysql:8.0.32
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: infra_workshop
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3308:3306
    volumes:
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/data:/var/lib/mysql
      - ./database/sql:/docker-entrypoint-initdb.d

  api:
    container_name: api
    tty: true
    depends_on:
      - db
    build:
      context: api/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    environment:
      DATABASE_HOST: database
      DATABASE_USER: app_user
      DATABASE_PASSWORD: password
      DATABASE: infra_workshop

  front:
    container_name: web
    build:
      context: front/
      dockerfile: Dockerfile.dev
    user: "${UID}:${GID}"
    command: ["yarn", "dev", "-p", "3001"]
    volumes:
      - ./front/app:/usr/src/app
    ports:
      - "4001:3001"
